### ISSUE TITLE
Inclusion of v8-profiler-node8 is causing node pre-gyp failures when installing on Node 10

### ISSUE THREAD

**Issue by ghost** [auth0/auth0-instrumentation#172]
# Reproduction steps
On Node 10:
1. Create a new project `mkdir example`
2. Initialize NPM `cd example; npm init`
3. Install auth0-instrumentation `npm i auth0-instrumentation`

# Expected
Package installs correctly.

# Received
```
2 warnings generated.
  CXX(target) Release/obj.target/profiler/src/heap_output_stream.o
sed: ./Release/.deps/Release/obj.target/profiler/src/heap_output_stream.o.d.raw: No such file or directory
  CXX(target) Release/obj.target/profiler/src/heap_graph_node.o
rm: ./Release/.deps/Release/obj.target/profiler/src/heap_output_stream.o.d.raw: No such file or directory
make: *** [Release/obj.target/profiler/src/heap_output_stream.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64"
gyp ERR! cwd /Users/mike/Code/example/node_modules/v8-profiler-node8
gyp ERR! node -v v11.10.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mike/Code/example/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:984:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/mike/Code/example/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mike/Code/example/node_modules/v8-profiler-node8
node-pre-gyp ERR! node -v v11.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64/profiler.node --module_name=profiler --module_path=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64' (1)
npm WARN example@1.0.0 No description
npm WARN example@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v8-profiler-node8@5.7.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-profiler-node8@5.7.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mike/.npm/_logs/2019-03-05T18_47_05_429Z-debug.log
C02VD5H0HTD8:example mike$ ../src/heap_graph_node.cc:2:10: fatal error: 'heap_graph_edge.h' file not found
#include "heap_graph_edge.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/profiler/src/heap_graph_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/mike/Code/example/node_modules/v8-profiler-node8/build/profiler/v5.7.8/node-v67-darwin-x64"
gyp ERR! cwd /Users/mike/Code/example/node_modules/v8-profiler-node8
gyp ERR! node -v v11.10.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by mikeops** [comment]
I ran into this issue trying to install auth0-instrumentation locally to test some Typescript definitions for the `auth0/types` package. Is it possible we could make the profiler an optional component in the install?

**Comment by nw** [comment]
resolved (issues with lock files)
